// Code generated by mockery v2.14.0. DO NOT EDIT.

package repositorymocks

import (
	ingredients "eccea/internal/brewbeer/ingredients"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryMock is an autogenerated mock type for the Repository type
type RepositoryMock struct {
	mock.Mock
}

// GetHop provides a mock function with given fields: idHop
func (_m *RepositoryMock) GetHop(idHop string) (*ingredients.Hop, error) {
	ret := _m.Called(idHop)

	var r0 *ingredients.Hop
	if rf, ok := ret.Get(0).(func(string) *ingredients.Hop); ok {
		r0 = rf(idHop)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ingredients.Hop)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(idHop)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMalt provides a mock function with given fields: idMalt
func (_m *RepositoryMock) GetMalt(idMalt string) (*ingredients.Malt, error) {
	ret := _m.Called(idMalt)

	var r0 *ingredients.Malt
	if rf, ok := ret.Get(0).(func(string) *ingredients.Malt); ok {
		r0 = rf(idMalt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ingredients.Malt)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(idMalt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetYeast provides a mock function with given fields: idYeast
func (_m *RepositoryMock) GetYeast(idYeast string) (*ingredients.Yeast, error) {
	ret := _m.Called(idYeast)

	var r0 *ingredients.Yeast
	if rf, ok := ret.Get(0).(func(string) *ingredients.Yeast); ok {
		r0 = rf(idYeast)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ingredients.Yeast)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(idYeast)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepositoryMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepositoryMock creates a new instance of RepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepositoryMock(t mockConstructorTestingTNewRepositoryMock) *RepositoryMock {
	mock := &RepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
