// Code generated by mockery v2.45.1. DO NOT EDIT.

package macerationmocks

import (
	maceration "eccea/internal/brewbeer/processes/maceration"

	mock "github.com/stretchr/testify/mock"
)

// ServiceMock is an autogenerated mock type for the Service type
type ServiceMock struct {
	mock.Mock
}

// EstimateBeer provides a mock function with given fields: params
func (_m *ServiceMock) EstimateBeer(params *maceration.Params) (*maceration.Results, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for EstimateBeer")
	}

	var r0 *maceration.Results
	var r1 error
	if rf, ok := ret.Get(0).(func(*maceration.Params) (*maceration.Results, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(*maceration.Params) *maceration.Results); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*maceration.Results)
		}
	}

	if rf, ok := ret.Get(1).(func(*maceration.Params) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EstimateColor provides a mock function with given fields: params
func (_m *ServiceMock) EstimateColor(params *maceration.Params) (*maceration.ColorResults, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for EstimateColor")
	}

	var r0 *maceration.ColorResults
	var r1 error
	if rf, ok := ret.Get(0).(func(*maceration.Params) (*maceration.ColorResults, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(*maceration.Params) *maceration.ColorResults); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*maceration.ColorResults)
		}
	}

	if rf, ok := ret.Get(1).(func(*maceration.Params) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EstimateFlavor provides a mock function with given fields: params
func (_m *ServiceMock) EstimateFlavor(params *maceration.Params) (*maceration.FlavorResults, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for EstimateFlavor")
	}

	var r0 *maceration.FlavorResults
	var r1 error
	if rf, ok := ret.Get(0).(func(*maceration.Params) (*maceration.FlavorResults, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(*maceration.Params) *maceration.FlavorResults); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*maceration.FlavorResults)
		}
	}

	if rf, ok := ret.Get(1).(func(*maceration.Params) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServiceMock creates a new instance of ServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceMock {
	mock := &ServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
