// Code generated by mockery v2.45.1. DO NOT EDIT.

package boilingmocks

import (
	boiling "eccea/internal/brewbeer/processes/boiling"

	mock "github.com/stretchr/testify/mock"
)

// ServiceMock is an autogenerated mock type for the Service type
type ServiceMock struct {
	mock.Mock
}

// EstimateFlavor provides a mock function with given fields: params
func (_m *ServiceMock) EstimateFlavor(params *boiling.Params) (*boiling.FlavorResults, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for EstimateFlavor")
	}

	var r0 *boiling.FlavorResults
	var r1 error
	if rf, ok := ret.Get(0).(func(*boiling.Params) (*boiling.FlavorResults, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(*boiling.Params) *boiling.FlavorResults); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*boiling.FlavorResults)
		}
	}

	if rf, ok := ret.Get(1).(func(*boiling.Params) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EstimateIBU provides a mock function with given fields: params
func (_m *ServiceMock) EstimateIBU(params *boiling.Params) (float64, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for EstimateIBU")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(*boiling.Params) (float64, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(*boiling.Params) float64); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(*boiling.Params) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServiceMock creates a new instance of ServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceMock {
	mock := &ServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
