// Code generated by mockery v2.14.0. DO NOT EDIT.

package boilingmocks

import (
	boiling "eccea/internal/brewbeer/processes/boiling"

	mock "github.com/stretchr/testify/mock"
)

// ServiceMock is an autogenerated mock type for the Service type
type ServiceMock struct {
	mock.Mock
}

// Do provides a mock function with given fields: params, useCaseKey
func (_m *ServiceMock) Do(params *boiling.Params, useCaseKey string) (*boiling.Results, error) {
	ret := _m.Called(params, useCaseKey)

	var r0 *boiling.Results
	if rf, ok := ret.Get(0).(func(*boiling.Params, string) *boiling.Results); ok {
		r0 = rf(params, useCaseKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*boiling.Results)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*boiling.Params, string) error); ok {
		r1 = rf(params, useCaseKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewServiceMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewServiceMock creates a new instance of ServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServiceMock(t mockConstructorTestingTNewServiceMock) *ServiceMock {
	mock := &ServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
