// Code generated by mockery v2.45.1. DO NOT EDIT.

package fermentationmocks

import (
	fermentation "eccea/internal/brewbeer/processes/fermentation"

	mock "github.com/stretchr/testify/mock"
)

// ServiceMock is an autogenerated mock type for the Service type
type ServiceMock struct {
	mock.Mock
}

// CalculateAlcoholByVolume provides a mock function with given fields: params
func (_m *ServiceMock) CalculateAlcoholByVolume(initialDensity, finalDensity float64) (float64, error){
	ret := _m.Called(initialDensity, finalDensity )

	if len(ret) == 0 {
		panic("no return value specified for CalculateABV")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(float64, float64 ) (float64, error)); ok {
		return rf(initialDensity, finalDensity)
	}
	if rf, ok := ret.Get(0).(func(float64,float64) float64); ok {
		r0 = rf(initialDensity, finalDensity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(float64)
		}
	}

	if rf, ok := ret.Get(1).(func(float64, float64) error); ok {
		r1 = rf(initialDensity, finalDensity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EstimateBeer provides a mock function with given fields: params
func (_m *ServiceMock) EstimateBeer(params *fermentation.Params) (*fermentation.Results, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for EstimateBeer")
	}

	var r0 *fermentation.Results
	var r1 error
	if rf, ok := ret.Get(0).(func(*fermentation.Params) (*fermentation.Results, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(*fermentation.Params) *fermentation.Results); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fermentation.Results)
		}
	}

	if rf, ok := ret.Get(1).(func(*fermentation.Params) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServiceMock creates a new instance of ServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceMock {
	mock := &ServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
