// Code generated by mockery v2.14.0.

package fermentationmocks

import (
	fermentation "eccea/internal/brewbeer/processes/fermentation"

	mock "github.com/stretchr/testify/mock"
)

// ServiceMock is an autogenerated mock type for the Service type
type ServiceMock struct {
	mock.Mock
}

// Do provides a mock function with given fields: params, useCaseKey
func (_m *ServiceMock) CalculateABV(params *fermentation.Params) float64 {
	ret := _m.Called(params)

	var r0 float64
	if rf, ok := ret.Get(0).(func(*fermentation.Params) float64); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(float64)
		}
	}

	return r0
}

type mockConstructorTestingTNewServiceMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewServiceMock creates a new instance of ServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServiceMock(t mockConstructorTestingTNewServiceMock) *ServiceMock {
	mock := &ServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
