// Code generated by mockery v2.44.1. DO NOT EDIT.

package maturationmocks

import (
	maturation "eccea/internal/brewbeer/processes/maturation"

	mock "github.com/stretchr/testify/mock"
)

// ServiceMock is an autogenerated mock type for the Service type
type ServiceMock struct {
	mock.Mock
}

// EstimateColor provides a mock function with given fields: params
func (_m *ServiceMock) EstimateColor(params *maturation.Params) string {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for EstimateColor")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(*maturation.Params) string); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewServiceMock creates a new instance of ServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceMock {
	mock := &ServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
